server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost/springcloud-db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
